### PR TITLE
obteniendo foto con una ruta diferente

### PR DESCRIPTION
**Pull request by ervinj1998**
en esta rama , verems las fotos con una ruta distinta. pero en las siguientes modificaciones podremos ver la foto que esta en el perfil.

### CODE REVIEW

**Comment by Hawaiideveloper** [comment]
@ervinj1998 looking like you are making some progress, I had to change a few things in the front end branch for the about field.  Please review the changes and add them accordingly

**Comment by Hawaiideveloper** [comment]
the card style css was looking pretty bad and artificial, so I did some edits

**Comment by Hawaiideveloper** [comment]
in the previous PR

**Comment by ervinj1998** [comment]
> @ervinj1998 looking like you are making some progress, I had to change a few things in the front end branch for the about field.  Please review the changes and add them accordingly


send the link of those changes now, to add them in the branch that I am working on right now which is the 154

**Pull request merged**
